<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CheckEolWorkloads>false</CheckEolWorkloads>
    <TargetFramework Condition="'$(WPRTargetPlatform)' != 'Android'">net8.0</TargetFramework>
    <TargetFramework Condition="'$(WPRTargetPlatform)' == 'Android'">net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net8.0-android'">26</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Xamarin.Essentials" Version="1.7.3" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Condition="'$(TargetFramework)' == 'net8.0-android'" Include="$(SolutionDir)\ThirdParty\DesktopNotifications\DesktopNotifications.Android\DesktopNotifications.Android.csproj" />
    <ProjectReference Include="$(SolutionDir)\ThirdParty\DesktopNotifications\DesktopNotifications.Windows\DesktopNotifications.Windows.csproj" />
    <ProjectReference Include="$(SolutionDir)\ThirdParty\DesktopNotifications\DesktopNotifications\DesktopNotifications.csproj" />
  </ItemGroup>

</Project>
