<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CheckEolWorkloads>false</CheckEolWorkloads>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
	<EmbeddedJar Include="Jar\com.arthenica.smartexception.jar" />
  </ItemGroup>
</Project>