<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-android;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
    <AndroidSupportedAbis>armeabi-v7a;arm64-v8a;x86;x86_64</AndroidSupportedAbis>
    <AndroidMinSdkVersion>26</AndroidMinSdkVersion>
    <AndroidTargetSdkVersion>34</AndroidTargetSdkVersion>
    <AvaloniaVersion>11.0.999-cibuild0023504-beta</AvaloniaVersion>
    <TrimMode>copyused</TrimMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="$(AvaloniaVersion)" />
    <PackageReference Include="XamlNameReferenceGenerator" Version="1.3.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WPR.UI\WPR.UI.csproj" />
  </ItemGroup>
</Project>
