<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <CheckEolWorkloads>false</CheckEolWorkloads>
    <TargetFramework Condition="'$(WPRTargetPlatform)' != 'Android'">net8.0</TargetFramework>
    <TargetFramework Condition="'$(WPRTargetPlatform)' == 'Android'">net8.0-android</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)\Core\WPR.Common\WPR.Common.csproj" />
  </ItemGroup>

</Project>
