<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>4.0.0</Version>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExCSS" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="HtmlAgilityPack.CssSelectors" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Windows.Compatibility" />
    <!--PackageReference Include="MonoGame.Framework.WindowsDX" /-->

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WPR.Common\WPR.Common.csproj" />
    <ProjectReference Include="..\WPR.WindowsCompability\WPR.WindowsCompability.csproj" />
  </ItemGroup>

</Project>
