<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net8.0-windows TFM, one for MacOS with net8.0-macos and one with net8.0 TFM for Linux.-->
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Mono.Cecil" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WPR.UI\WPR.UI.csproj" />
    <ProjectReference Include="..\Microsoft.Phone\Microsoft.Phone.csproj" />
    <ProjectReference Include="..\Microsoft.Xna.Framework.GamerServices\Microsoft.Xna.Framework.GamerServices.csproj" />
    <ProjectReference Include="..\WPR.Common\WPR.Common.csproj" />
    <ProjectReference Include="..\WPR.MonoGameCompabilityPatch\WPR.MonoGameCompability.csproj" />
    <ProjectReference Include="..\WPR.WindowsCompability\WPR.WindowsCompability.csproj" />
  </ItemGroup>
</Project>
