<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CheckEolWorkloads>false</CheckEolWorkloads>
    <TargetFramework Condition="'$(WPRTargetPlatform)' != 'Android'">net8.0</TargetFramework>
    <TargetFramework Condition="'$(WPRTargetPlatform)' == 'Android'">net8.0-android</TargetFramework>
    <Nullable>enable</Nullable>
    <Version>8.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)\Core\WPR.WindowsCompability\WPR.WindowsCompability.csproj" />
  </ItemGroup>
</Project>
