<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
     <TargetFrameworks>net8.0-windows10.0.26100.0</TargetFrameworks>
  </PropertyGroup>


  <PropertyGroup>
    <EFVersion>6.0.8</EFVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <PropertyGroup>
    <AvaloniaVersion>11.0.999-cibuild0023504-beta</AvaloniaVersion>
    <TrimMode>copyused</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  
  
  <ItemGroup>
    <None Update="FAudio.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ffmpeg.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FNA3D.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FNWP72.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SDL2.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
 
    <TrimmableAssembly Include="Avalonia.Themes.Fluent" />
    <TrimmableAssembly Include="Avalonia.Themes.Default" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
    <PackageReference Include="XamlNameReferenceGenerator" Version="1.3.4" />
  </ItemGroup>
 
  <ItemGroup>
    <ProjectReference Condition=" '$(OS)' == 'Windows_NT' " Include="$(SolutionDir)\UI\WPR.UI\WPR.UI.csproj" />
  </ItemGroup>
  <Target Name="Copy pre-made database" AfterTargets="Build">
	
    <ItemGroup>
	  <_CopyItems Include="$(SolutionDir)Database\**\*.*" />
	</ItemGroup>
    
	<Copy SourceFiles="@(_CopyItems)" DestinationFolder="$(OutputPath)\Database\%(RecursiveDir)" SkipUnchangedFiles="true" OverwriteReadOnlyFiles="true" />
  </Target>
</Project>
